### ISSUE TITLE
Annoying bug (framerate depending on window size)

### ISSUE THREAD

**Issue by wasserwiesel** [jacobbo/WebEye#36]
When playing an RTSP video:
The larger the window, the fewer frames

When playing an RTMP video:
The larger the window, the more frames

This error was tested with different and fast computers. The behavior was always as described above.
It would be nice if you would fix this error 👍 
Thank you very much! Otherwise, the player is very good.
Only the possibility is missing, that one can put other elements over the player.

**Comment by jacobbo** [comment]
How do you count frames?

**Comment by wasserwiesel** [comment]
I see that the picture jerks ...

**Comment by wasserwiesel** [comment]
Something seems wrong with the allocated CPU power. If the window is smaller (RTMP), it also gets less CPU power, resulting in a very low frame rate.

I have testet it on Window 10 and Windows Server 2012

**Comment by wasserwiesel** [comment]
Okay, that would be great Thanks!
You can see the behavior well in the Task Manager, if you look at an RTMP stream and then pull the window larger. Then the CPU load gets bigger and the picture gets better.

**Comment by wasserwiesel** [comment]
I am currently testing with the FFmpeg library, would you mind, telling me the parameters you are passing ffplay? Your streaming is very fast and when the stream pile up, it automatically skips the old ones and spools up, that's very good!

**Comment by jacobbo** [comment]
it's just
ffplay.exe your_stream_url

**Comment by jacobbo** [comment]
Please let me know if ffplay shows the same weird behaviour.

**Comment by wasserwiesel** [comment]
I have just tested it, it does not have the behavior, it runs smoothly.
Okay yes thats (ffplay.exe your_stream_url) the normal way, I thought you might added some specific parameters, because with ffplay my stream does not skip frames. Then I will continue to search for the parameter

**Comment by jacobbo** [comment]
Sorry, I do not use any specific parameters in my code.

**Comment by wasserwiesel** [comment]
Hm strange. I wonder why the delay on your player is so small. Even if I set all parameters with ffplay to reduce latency, I have a delay twice as long as you...magic? :D

**Comment by wasserwiesel** [comment]
Would you mind sending me your ffplay built? Thant would be great!

**Comment by jacobbo** [comment]
You can download ffplay from here: https://ffmpeg.zeranoe.com/builds/

**Comment by wasserwiesel** [comment]
Yeah I did and tested all different build they offer, but none is as good as yours. Somehow your player has a much smaller delay and even when the network bandwith was reduced for a few seconds, it always jumps back to the latest frame.
Whats your secret? :D I have testet all diffenrent parameters for ffplay to reduce framerate, but none of them satifites me. Meanwhile, I can also put elements on top of your player.
Of course, I would simply use your player if it were not the problem with the slow frame rate.

**Comment by jacobbo** [comment]
Well, my implementation differs from ffplay. ffplay handles audio and subtitles streams, supports seeking, etc., while my implementation does not do this stuff. I'd be happy to reproduce ffplay's implementation, but it's too complicated, partially, due to historical reasons, I believe. In other words, I use my own algorithm to schedule frames for rendering. Also, I use new FFmpeg api for decoding frames, while ffplay uses the old api for this.

**Comment by wasserwiesel** [comment]
Hm okay, I see. I thought so. Do you think you will be able to keep the frame rate stable when changing the window size in the future? I am not sure if I can develop my own player based on ffmpeg. That does not seem easy...

**Comment by jacobbo** [comment]
I'm rewriting the frame scaling code now, plan to finish it this weekend. Hopefully, this will solve the frame rate issue.

**Comment by wasserwiesel** [comment]
Wow, that sounds good! I'm looking forward to it and will test it.

**Comment by frankpc3** [comment]
Thank you Alexander for all your hard work on this.  I use it everyday to display video with my home alarm and automation system.  Looking forward to your improvements.

**Comment by jacobbo** [comment]
@frankpc3, thanks for your feedback)

@wasserwiesel I was unable to come up with a better frame scaling code. I'll leave the current implementation in place for now. Can you see the 'fewer frames' issue with this rtsp stream?
rtsp://184.72.239.149/vod/mp4:BigBuckBunny_115k.mov

**Comment by wasserwiesel** [comment]
That's a pity, I was looking forward to it. Maybe someday you will come up with a possibility in the future. Nevertheless, many thanks for your efforts

**Comment by jacobbo** [comment]
Well, I easily believe you in the first part of your description "The larger the window, the fewer frames", but it's hard to believe in the RTMP part: "The larger the window, the more frames".  I'll try to add a fps counter and we could measure it for your streams.

**Comment by frankpc3** [comment]
I haven't measured frames but I have noticed that the larger the window, the more load on the cpu.  I tried putting the control on a small Windows 10 RCA "Cambio" tablet - a four core Intel Atom processor @ 1.6 or so.  The stream works well with a small window.  But with a full screen (10.1"), the .NET timers cannot keep up due to high cpu usage.  (WPF template)

Is there a way to just display the native resolution of the stream without any re-encoding such that cpu usage is minimized?

**Comment by jacobbo** [comment]
It turned out that the main CPU consumer is the StretchDIBits function, which scales a frame to fit the control's window. The larger window, the more scaling needed, the more CPU usage. As you pointed out, the way to lower CPU usage is to reduce the control's window size. The original frame size can be retrieved using the control's property: 

///
/// Gets the unstretched frame size, in pixels.
///
public Size VideoSize  { get; }
 
If you set the control's window to this size there should be no scaling at all.

**Comment by frankpc3** [comment]
I've modified my script to adjust the control's window size based on the "VideoSize".  
Doing so seems to help the little computer.
Thanks!

**Comment by wasserwiesel** [comment]
Did you change anything? Since yesterday the RTSP and RTMP stream are doing much better!

**Comment by jacobbo** [comment]
Nothing. Much better in what sense?

**Comment by wasserwiesel** [comment]
No matter how big the window is, it almost runs smoothly (on all computers) I have not changed anything either?? Of course I use your WPF demo project! I estimate the frame rate is now close to 25fps. But the delay is very good. I have the player built into my project now, thank you very much, good job!

**Comment by jacobbo** [comment]
Well, make sure you're using the latest version of the nuget package. The current version is 1.0.4.
